# Yaml file start ---
---
# create a script to configure nginx in our web server

# who is the host - means name of the server
- hosts: web

# gather data
  gather_facts: yes

# we need admin access
  become: true

# add the actual instructions
  tasks:
  - name: Install/configure Nginx Web server in web-VM
    apt: pkg=nginx state=present
#can be absent as well
# we need to ensure at the end of this script the status of nginx is running